[package]
name = "tetris_client"
version = "0.1.0"
authors = ["Bram Buurlage <brambuurlage@gmail.com>"]
edition = "2018"

[dependencies]
tetris_model = { path = "../model" }
serde = "1"
serde_json = "1"
quicksilver = "0.3.7"
mirror = { path = "../../mirror" }
rand = "0.6"