[package]
name = "tetris_server"
version = "0.1.0"
authors = ["Bram Buurlage <brambuurlage@gmail.com>"]
edition = "2018"

[dependencies]
tetris_model = { path = "../model" }
serde = "1"
serde_json = "1"
mirror = { path = "../../mirror" }
clap = "2"
